### ISSUE TITLE
Synctex data not available when latex file resides in a path containing danish special chars

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#601]
```
What steps will reproduce the problem?
1. Create a new directory with a name that contains at least one danish special 
char (ie. one of 'æøå')
2. Create a latex file in this directory.
3. Compile the latex file from texworks
4. Control click on the source to open the pdf window pane
5. "No SyncTex data available" is displayed in the bottom of the pdf window 
pane.
6. Synchronization between code and pdf does not work.
7. The problem can be fixed by renaming the directory to a name without danish 
special chars.

What is the expected output? What do you see instead?
Expected: That synctex works
Observed: Synctex is not working

What version of the product are you using? On what operating system?
Version: 0.5 r979
Windows 7

Please provide any additional information below.
The same document / path structure works fine under linux (ubuntu 12.04)
```

Original issue reported on code.google.com by `henrikmidtiby@gmail.com` on 1 Oct 2012 at 9:08

**Comment by stloeffler** [comment]
This issue pertains to a long-outdated version of TeXworks and Qt. Therefore it will be closed for now. Should the issue persists in the latest version, it can be reopened of course.

**Comment by ColourGrey** [comment]
It seems that this bug is back again. I saved a LaTeX file under a name containing diacritics (more specifically, the character "ț"). After compilation TeXstudio complained that "No SyncTeX data available". It was enough to change "ț" into "t" (i.e. to get rid of the diacritics), in order for SyncTeX to work properly.

TeXstudio 4.3.1, Qt 6.3.1, on Windows 10 x64.
