### ISSUE TITLE
Double click word selects whole line

### ISSUE THREAD

**Issue by avelure** [TeXworks/texworks#700]
After version TeXworks-w32-0.5-r1379 double-clicking a word selects the whole line (ala triple clicking) instead of only the word as before

**Comment by UniqMartin** [comment]
Have you tried version 0.4.6, available from the [releases page](https://github.com/TeXworks/texworks/releases)? While the version number is lower, it is actually more recent than the test build you are using and includes all of its features. On Windows 7 (32-bit) I get the expected behavior with that build.

**Comment by avelure** [comment]
I didn't see there was a new stable and updated from the test builds on habit. 
0.4.6 works fine.

**Comment by UniqMartin** [comment]
I'm glad it works for you, too. If you're happy with it, feel free to close this issue.
