### ISSUE TITLE
Auto Indent

### ISSUE THREAD

**Issue by siscia** [TeXworks/texworks#701]
Hi :)

it is auto indent available in TeXworks ?

I would like to have a behaviour such as
`\begin{whatever} [ENTER]` and on the next line find the cursor 4 (2 ?) spaces on the right.
Similarly with `\end{whatever}[ENTER]` it would be awesome to find the cursor back 4 spaces on the left.

Is something like this available ?

Greets

**Comment by UniqMartin** [comment]
I don't think this is supported right now, also because this would be specific to LaTeX and TeXworks tries to be mostly format-agnostic. But I agree that this would be a nice feature to have.

What it does though, and what is sufficiently convenient for me, is that once you indent a line, it keeps that indentation for the next line. (You might have to enable this via “Auto-indent Mode” in the “Format” menu.) For example, once you enter
```tex
\begin{whatever}
    Some text.
```
and manually indent “Some text.”, pressing enter after this will auto-indent the next line. Does that help or were you already aware of this?

**Comment by siscia** [comment]
Hi :)

Yes I was already aware of the "Keep Indent Mode" :)

I completely understand your point and I find it very solid.

Thanks for your time,

Cheers :)

**Comment by UniqMartin** [comment]
Note that this is just my personal opinion. I'm only a user, not the developer of TeXworks. :)

**Comment by siscia** [comment]
My question was simply if the auto indent mode was present.

Your answer is more than complete for me :+1:
