### ISSUE TITLE
Double click selects the whole line

### ISSUE THREAD

**Issue by nignasi** [TeXworks/texworks#706]
When I make double click on a word for selecting it, the whole line is highlighted. I thing this is a wrong behaviour.

I'm using Texworks 0.4.6 (official) [r c29723a, 03/04/2015] on windows 8 (x64)

**Comment by UniqMartin** [comment]
Which version does appear after the text “Qt application framework” in the About TeXworks dialog?

I'm asking because the Windows binaries were re-uploaded once after the initial release. Maybe you are still working with the original binaries, that were built with an older Qt version. If your Qt version is older than 5.4.1, then please try to re-download and reinstall. I believe the new build might have solved that issue, but I have no Windows machine available right now to confirm my suspicion.

**Comment by nignasi** [comment]
My TeXworks is using Qt 5.10. 

I've two windows install texworks:

TeXworks-setup-0.4.6-20150403-git_c29723a_Qt51.exe and 
TeXworks-setup-0.4.6-20150403-git_c29723a.exe

both downloaded from 

https://drive.google.com/folderview?id=0B5iVT8Q7W44pSENVdWlRMmw3RlE&tid=0B5iVT8Q7W44pMkNLblFjUzdQUVE#list

Which one should I install? Is any newer version?

**Comment by UniqMartin** [comment]
That's definitely the older build. Please download and try the official release available here on GitHub and see if that fixes your issue: https://github.com/TeXworks/texworks/releases/tag/release-0.4.6

**Comment by nignasi** [comment]
Works. Problem solved. Thank you

**Comment by UniqMartin** [comment]
You're welcome. Glad I could help you.
