### ISSUE TITLE
Suggestions on the new pdf viewer

### ISSUE THREAD

**Issue by lowai** [TeXworks/texworks#735]
1. When it is rendering, there seems some background with small text that flashes. This is annoying. Is it possible to replace it with a white/blank background?
2. The zoom in/out looks harder to control than before. Maybe use a smaller step size for zoom in/out. I end up manually setting it to 85% scale to show the text body on letter page with 1in margin around on my 1920 x 1080 screen.

**Comment by stloeffler** [comment]
ad 1: This is indeed possible as the string that is displayed ("rendering page") is translatable. So you can create a translation file where you "translate" the string by an empty string.

ad 2: the scale factor is different, but not too much. Previously, it was 1.41 (sqrt(2)) while at the moment it is 1.5. The new value has the advantage that it gives "simple" zoom factors (e.g., 100%, 150%, 225%...) instead of irrational numbers. Also note that a (very) fine step size would theoreticall< give a "smoother" zooming experience, but would also result in the need to re-render the page over and over with just slightly different zoom factors. That might cause substantial lag and flickering.

**Comment by lowai** [comment]
Not 'smooth' zooming experience... I just need to be able to adjust the
zoom factor such that the text width of the document (not the paper width)
fits the preview window...

**Comment by Markvy** [comment]
The old version of TeXworks (0.4.x) used to transition directly from the old document to the new one.  The new one has an intermediate stage old ---> rendering ---> new.  It would be really nice if the old behavior came back,  It was really nice to make small tweaks to the tex file, and see how the preview changed (say, move something by a fraction of an inch).  Now the flash makes me lose my place so it's hard to see what changed.  (On the other hand, I am really enjoying the luxury of smooth scrolling!)

**Comment by dhslichter** [comment]
I agree with this sentiment; the "rendering page" interlude is frustrating and makes it hard to look at small changes in a document.

**Comment by Markvy** [comment]
If this is fixed in 6.2 that's super neat.
