### ISSUE TITLE
TeXworks randomly hangs and opens files really slow

### ISSUE THREAD

**Issue by ashipunov** [TeXworks/texworks#771]
_Steps to reproduce the problem_:

1. Download my working copy of book from http://ashipunov.info/shipunov/school/biol_240/en/visual_statistics.tex
2. Try top open it in TeXworks, for me, it takes now ~ 1min!
3. Hanging is not reproducible, despite of all my efforts I cannot spot the reason. It happens randomly on several machines, all under Ubuntu MATE 16.04, and is extremely annoying

_Expected output_: Before my upgrade to 16.04 and to 0.6.1, it worked several times faster. The same file opened in seconds. Hanging did not occur. Now this is a pain. I am thinking to switch to some other TeX editor. This is a pity because I liked TeXworks. I tried to compile 0.4.5 but slowness did not disappear.

_Actual output_: NA

_TeXworks version_:  Version 0.6.1 (launchpad) [r.3614278, 5/1/16 3:43 AM]
_TeXworks obtained from_:  Ubuntu stable PPA
_Operating system_:  Ubuntu MATE 16.04

_Please provide any additional information below_:

**Comment by ashipunov** [comment]
P.S.
I compiled new TeXworks from Git. Same problems. However, I found that TeXWork crashes (both 0.6.1 and 0.7) when I change hyphen to underscore ;) Very interesting!
0.4.5 (Version 0.4.5 r.1280 (personal)) does not crash on that operation, and also opens my file in ~ 30 sec (still slow but much faster) so I might stay on 0.4.5 (I compiled it from SVN in June when I first discovered the slowness but those time I did not see these crashes yet).

**Comment by ashipunov** [comment]
I found another two reasons why 0.4.5 is better than 0.6.1:
1) When it opens file, it shows spinning wheel cursor whereas 0.6.1 window shows nothing, just do not react until the file is fully loaded (which takes plenty of time)
2) Internet hyperlinks work in PDF viever (in 0.6.1, they did not)

**Comment by ashipunov** [comment]
In all, I think that I already found at least three bugs in 0.6.1

**Comment by ashipunov** [comment]
I started to suspect now that my problems could be related with Qt version. Nevertheless, I really want to hear from developers what they recommend.

**Comment by stloeffler** [comment]
First of all: sorry to hear you have so many problems with TeXworks.
Unfortunately, I could not reproduce them.

 * For me, the document loaded in ~1s (this was for Qt 5.5.1, FWIW). Some differences in load time might be due to the hardware and other programs running at the same time, but usually it should not be nearly as bad as you reported (unless of course you are running so me heavy calculations in the background or something). Do both the tex and the pdf window appear at (roughly) the same time, or first the one and then the other? If they don't appear simultaneously, how long until the first/second window appears?
 * "Changing a hyphen to an underscore": do you mean in the filename or in a particular line? If it is a particular line, could you ensure line numbers are displayed (in the Format menu) and then check if something weird is going on with said line numbers (which might hint at issue #469)?
 * Internet hyperlinks work for me. Does the cursor change to a hand icon? If you hover over the link for a few seconds, do you see a tooltip pop up with the URL? If you click on it, do you see a dialog box appearing?
 * Regarding Qt: Qt5 is the default, unless either a) you only update the code but reuse the build files from an earlier, Qt4 build or b) some part or other (usually development headers) of Qt5 is not found. To rule out point a, could you create a new build directory and run CMake from scratch there? If it still does not pick up Qt5, there are probably some packages missing

That said, apart from Qt, there is also the poppler library (used for processing and displaying the PDF) that might play an important role in many of these issues. Note that you also need the proper poppler-qt version matching your Qt version.

So, my overall recommendation: make sure you have Qt5 and poppler-qt5 (with development headers) installed (e.g. using `sudo apt-get install qtbase5-dev qtscript5-dev qttools5-dev zlib1g-dev libhunspell-dev libpoppler-qt5-dev libpoppler-private-dev liblua5.3-dev`). Create a new build directory,  run CMake in it, and build TeXworks. Then check the points I mentioned above.

Hope this helps!

**Comment by ashipunov** [comment]
Dear Stefan,

First, let me express my gratitude to the TeXworks developers and
maintainers. I am not a TeX expert but I work with TeX since 1995 and
developed some LaTeX packages. From 2010, TeXwork is my main TeX tool.
All my lecture slides, lab materials, manuals and several books were
made with TeXworks. Thank you. I write this also to let you know how
important TeXworks is for me.

Now to your questions and suggestions. Let me answer them first for
the Version 0.6.1 (launchpad) [r.3614278, 5/1/16 3:43 AM] which was
installed using stable Ubuntu PPA. As far as can I see, it was
compiled under Qt 4.8.7. I will test it on my workplace computer which
I consider quite powerful (8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz;
memory 16314MB (2429MB used); Ubuntu 16.04.1 LTS 4.4.0-59-generic
#80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64
GNU/Linux):

> For me, the document loaded in ~1s (this was for Qt 5.5.1, FWIW). Some differences in load time might be due to the hardware and other programs running at the same time, but usually it should not be nearly as bad as you reported (unless of course you are running so me heavy calculations in the background or something).

1) The document of question loads in 29 sec (this is the time after
which the TeXwork window start to be responsive to typing).

> Do both the tex and the pdf window appear at (roughly) the same time, or first the one and then the other? If they don't appear simultaneously, how long until the first/second window appears?

2) Almost simultaneously, PDF window delays about ~ 1 sec (but it is
as irresponsible as text window, and I remember that smoothing do not
appear sometimes -- however, when I checked today, smoothing worked
from the beginning). Also, sometimes it shows the first page but
sometimes in shows only slanted "rendering page" messages.

3) By the way, TeXworks seemingly wanted to open the file with the
last editing position. Unfortunately, it frequently does it wrong, I
just check it and that happened again. (Same was on 0.4.5 under my
Ubuntu Lucid). This is not a bug, just a bit annoying. Now when I
follow this more attentively, I start to suspect that TeXworks open my
file simply in random places...

> "Changing a hyphen to an underscore": do you mean in the filename or in a particular line? If it is a particular line, could you ensure line numbers are displayed (in the Format menu) and then check if something weird is going on with said line numbers (which might hint at issue #469)?

4) There was a string (piece or R code) 'png(file="1-20.png",
bg="transparent")' which I wanted to change (and finally changed, with
mcedit) to 'png(file="01_20.png", bg="transparent")'. On my home
laptop, both 0.6.1 and 0.7 crashed immediately. On my current
workplace computer, I cannot reproduce it.

5) By the way, I remember another annoying issue. Sometimes, rows of
text just disappear from the text window. Workaround is unwrap lines
and wrap them again.

> Internet hyperlinks work for me. Does the cursor change to a hand icon? If you hover over the link for a few seconds, do you see a tooltip pop up with the URL? If you click on it, do you see a dialog box appearing?

6) Cursor changes to hand icon, yes, but clicking produce no effect.
Tooltip does not appear. No dialog box.

> Regarding Qt: Qt5 is the default, unless either a) you only update the code but reuse the build files from an earlier, Qt4 build or b) some part or other (usually development headers) of Qt5 is not found. To rule out point a, could you create a new build directory and run CMake from scratch there? If it still does not pick up Qt5, there are probably some packages missing
> That said, apart from Qt, there is also the poppler library (used for processing and displaying the PDF) that might play an important role in many of these issues. Note that you also need the proper poppler-qt version matching your Qt version.
> So, my overall recommendation: make sure you have Qt5 and poppler-qt5 (with development headers) installed (e.g. using sudo apt-get install qtbase5-dev qtscript5-dev qttools5-dev zlib1g-dev libhunspell-dev libpoppler-qt5-dev libpoppler-private-dev liblua5.3-dev). Create a new build directory, run CMake in it, and build TeXworks. Then check the points I mentioned above.

Let me do it now. I will follow your recommendations and also
https://github.com/TeXworks/texworks/wiki/Building:

7) The following additional packages will be installed: liblua5.3-0.
The following NEW packages will be installed: liblua5.3-0
liblua5.3-dev libpoppler-private-dev libpoppler-qt5-dev
qtscript5-dev... Done.

8) cmake reports:

===
TeXworks has been configured:
  Version:                             0.7.0
  Git Commit:                          caf3463 (2017-01-15 18:52:45 +0100)
  Build ID:                            personal
  Qt version:                          5.5.1
  Compiler optimization:               Release
  Lua scripting plugin:                yes
...
===

(By the way, I _have_ muPDF development libraries but for some reason
cmake says: "MuPDF backend: no")

Compiled and installed. Now I will answer same questions but with the
new TeXworks (Version 0.7 (personal) [r.caf3463, 2017-01-15 11:52 AM],
Qt v5.5.1):

1) 20 sec

2) Small transparent text window appears first with spinning wheel,
then after ~19 sec it restores to the full size and PDF window
immediately appears.

3) Opens on some random position but when you start to move cursor,
you are in the place of previous editing. Maybe, it was a case
previously?

4) Underscore crash did not reproduce.

6) Now it all works! Tooltip, dialog and finally everything opens in Firefox.

Now I answer same questions with another TeXworks, Version 0.4.5
r.1280 (personal) compiled under Qt 4.8.7:

1) 14 sec

2) Text window (with text) appears with the spinning wheel first, then
after ~ 13 sec PDF window appears.

3) Opens on some random position but when you start to move cursor,
you are in the place of previous editing.

4) Underscore crash did not reproduce.

6) Tooltip appears, no dialog (I believe as it should be in this
earlier version), opens well in Firefox.

All in all, I am going to stay with 0.4.5 at the moment. I cannot
prove it, but I hope that this version is also free from disappearing
rows and accidental hangs. And 6 seconds is important, especially if
you open your document many times a day.

But I would prefer to switch to new TeXworks and Qt 5 if possible when
my issues are resolved. Here I hope you can help me.

With best wishes,

Alexey

**Comment by stloeffler** [comment]
Thanks for the extensive testing! The most important thing first: I could reproduce your problem now. It is caused by the spell checker (which wants to check the whole file, taking a lot of time). Can you confirm that disabling the spell checking (e.g. using `%!TeX spellcheck=None` at the top of the file, then saving and reopening) does workaround the long loadtime issue for you as well?

3) The file should be opened with the cursor at the last editing position (if known). From your report, it seems that the view does not scroll properly to that position, though - I have to check that in more detail.

4+5) disappearing lines and random crashes do indeed hint strongly as #469 

6) No tooltip (and no dialog for 0.6.x) is an indication that the hyperlink was not recognized correctly. Can you tell me one particular hyperlink that showed this behavior (as there are many, maybe just some of them don't work?).

8) MuPDF support is a side project that is not fully functioning yet. Therefore it is disabled by default (even if you have the headers) unless you explicitly request it being turned on (which is not recommended ATM unless you want to do some programming ;-)).

**Comment by ashipunov** [comment]
Dear Stefan,

> Thanks for the extensive testing! The most important thing first: I could reproduce your problem now. It is caused by the spell checker (which wants to check the whole file, taking a lot of time). Can you confirm that disabling the spell checking (e.g. using %!TeX spellcheck=None at the top of the file, then saving and reopening) does workaround the long loadtime issue for you as well?

Good news! With %!TeX spellcheck=None, 0.4.5 opens file by 1.5 sec.
Same is newly built 0.7. However, 0.6.1 from launchpad stable opens it
in 14 sec. This is weird...

So what do you recommend? On my Ubuntu Lucid TeXworks 0.4.x, I did not
remember this problem, spellchecker or not. Is it a bug? Or the
feature of newer spellcheckers? How to speed up the file loading if I
still need to check my spelling (for me, this is one of key features
in TeXworks)?

> The file should be opened with the cursor at the last editing position (if known). From your report, it seems that the view does not scroll properly to that position, though - I have to check that in more detail.

"view does not scroll properly to that position" -- thanks, this is a
correct description of what I see.

> 4+5) disappearing lines and random crashes do indeed hint strongly as #469

Well, I have read this thread but I am not sure if this describes my
problem since I almost never use line numbers... Could this happen
without visible line numbers?

> No tooltip (and no dialog for 0.6.x) is an indication that the hyperlink was not recognized correctly. Can you tell me one particular hyperlink that showed this behavior (as there are many, maybe just some of them don't work?).

Sure, for example on "http://ashipunov.info/shipunov/open". However,
what is really strange, there is tooltip now! (I run my 0.6.1 as
"/usr/bin/texworks visual_statistic.tex"). But no dialog and link does
not open in browser. Oh, even more strange -- tooltip disappeared. I
re-run the editor but no tooltips. Looks like it is shown only when
file was open first time, and only for small time...

> MuPDF support is a side project that is not fully functioning yet. Therefore it is disabled by default (even if you have the headers) unless you explicitly request it being turned on (which is not recommended ATM unless you want to do some programming ;-)).

OK, thanks for explanation. I like muPDF and use it as my main PDF
viewer, this is why I asked.

With best wishes,

Alexey

**Comment by ashipunov** [comment]
Dear Stefan,

This is wonderful, thank you! Happy Easter!

Alexey

2017-04-16 12:53 GMT-05:00 Stefan Löffler <notifications@github.com>:
