### ISSUE TITLE
TeXworks'PDF previewer cannot display Chinese fonts, but the generated pdf file can be displayed correctly in Adobe Acrobat Reader.

### ISSUE THREAD

**Issue by mathada** [TeXworks/texworks#779]
#_Steps to reproduce the problem_:

```
% xeLaTeX for compiling
\documentclass{ctexart} 
\usepackage{fontspec}

\setCJKmainfont[
BoldFont=Adobe Heiti Std,
ItalicFont=Adobe Kaiti Std,
SmallCapsFont=Adobe Heiti Std
]{Adobe Song Std}
\setCJKsansfont{Adobe Heiti Std}
\setCJKmonofont{Adobe Fangsong Std}

\setmainfont{Lucida Sans}

\begin{document}

中文字体
abc ABC

\end{document}
```

The Chinese fonts disappears in PDF previewers, but the generated pdf file can be displayed correctly in Adobe Acrobat. English fonts display has no problem.

_TeXworks version_: 0.6.1
_TeXworks obtained from_: CTeX 
_Operating system_: Windows 10

**Comment by stloeffler** [comment]
Thanks for reporting. This seems to be a problem with the CTeX distribution though - please report the issue to them.

Background: I tested this with the official TeXworks binary available at https://github.com/TeXworks/texworks/releases and the glyphs displayed correctly (on Windows 7 and Windows 8.1). Then I tried with the MiKTeX-supplied version and the glyphs did not display. This happens because Chinese fonts need some additional encoding files that are supplied with the official build, but apparently are not included in your distribution (or are moved somewhere where TeXworks can't find them). BTW: there is a testcase for this available at https://github.com/TeXworks/texworks/tree/master/testcases
