### ISSUE TITLE
PDF viewer does not render images

### ISSUE THREAD

**Issue by MBradbury** [TeXworks/texworks#792]
_Steps to reproduce the problem_:

1. Compile the attached code [min.zip](https://github.com/TeXworks/texworks/files/1071291/min.zip)
2. View the PDF and see it has a white square where the image is expected ![blank](https://user-images.githubusercontent.com/2089920/27081736-a6ae4d2c-5039-11e7-801c-51e2a62e2c71.png)

_Expected output_:
Open the PDF in Adobe and observe the image is present ![notblank](https://user-images.githubusercontent.com/2089920/27081741-ac85e1ce-5039-11e7-836f-63c96ee587b8.png)

_TeXworks version_:  0.6.2
_TeXworks obtained from_: MikTex
_Operating system_: Windows 10 Pro x64 (1703 build 15063.332)

**Comment by MBradbury** [comment]
Not that this does not appear to happen for all types of images.

PDF images have rendered correctly, as have png images.

**Comment by stloeffler** [comment]
Thanks for reporting. In a quick test (albeit not on Windows 10), the official TeXworks build downloaded from this site (github) seemed to work fine for me. If that build works for you as well (you can just unzip it and try it), the issue is with the MiKTeX build and should be reported to the MiKTeX developers...

**Comment by MBradbury** [comment]
My quick test also confirms this. I'll report this to MiKTeX.

**Comment by MBradbury** [comment]
Reported to MiKTeX at https://sourceforge.net/p/miktex/bugs/2608/
