### ISSUE TITLE
Fine synchronisation from pdf to tex fails

### ISSUE THREAD

**Issue by jlaurens** [TeXworks/texworks#802]
Problem : TW relies on false assumptions to synchronize from pdf to tex, this is why sometimes it fails 

Here is how it works. When the user clicks the pdf, TW retrieves the source file and the line number from the node given by the synctex scanner. In order to fine tune the synchronisation, TW looks for the text in the pdf, around the click location. For that purpose, TW asks the scanner for a tex to pdf synchronization, then searches the answer for the box containing the hit point. TW is then assuming that all the nodes will be given by the scanner, in furthermore in some appropriate ordering. This is definitely not a good assumption and causes synchronisation failures, in general near the top or the bottom of a paragraph.

The correct solution is to ask the first node for geometrical information.
1) add a `QRectF` field to `TeXSyncPoint`
```
  struct TeXSyncPoint {
    QString filename;
    int line;
    int col;
    QRectF rect;// <-----------
  };
```
2) Init that new property in `TWSyncTeXSynchronizer::syncFromPDF` after `retVal.col = -1;`
```
      retVal.line = SyncTeX::synctex_node_line(node);
      retVal.col = -1;
      retVal.rect = QRectF(synctex_node_box_visible_h(node),
                        synctex_node_box_visible_v(node) - synctex_node_box_visible_height(node),
                        synctex_node_box_visible_width(node),
                        synctex_node_box_visible_height(node) + synctex_node_box_visible_depth(node));
```
3) Use it in `TWSyncTeXSynchronizer::_syncFromPDFFine` by replacing the test at lines 220 (~) onwards, which uses forward synchronisation
```
    if (SyncTeX::synctex_display_query(_scanner, dest.filename.toLocal8Bit().data(), dest.line, -1, src.page) > 0) {
    SyncTeX::synctex_node_p node;
    while ((node = SyncTeX::synctex_scanner_next_result(_scanner)) != NULL) {
      ...
    }
  }
```
by one single line
```
selection.append(dest.rect);
```

That's all. My C++ and Qt skills are very low such that this code might be optimised with no difficulty.

Please notice that it has been successfully tested with the latest synctex.

Moreover, this solves the problem for long lines with many similar words.

**Comment by stloeffler** [comment]
Thanks for your suggestion. However, your description of how the process is intended to work is not entirely accurate. It should be as follows:
### General Idea
1) Perform "coarse" synchronization (i.e., get the tex file name and line number)
2) Get the text of the line (both from the tex and the pdf)
3) Find a 1:1 correspondence of a portion of the text, starting with the character the user clicked on and growing as necessary

### Detailed description
1) Perform "coarse" synchronization (i.e., get the tex file name and line number)
2) Do a forward sync (tex->pdf) for the whole line (by passing 0 as column number) and store the returned rectangles. Here, it is assumed that the returned list of nodes encloses all content of the line (=paragraph), but no other line [l 218-229]. No assumption about ordering of SyncTeX nodes is made
3) From the pdf, extract the text enclosed by (the union of) the rectangles. Here, it is assumed that the _pdf boxes_ are ordered according to the reading direction; if they are not, there is no easy way ATM to actually extract the text. [l 232]
4) Determine on which _pdf character box_ the user clicked and determine the corresponding column in the extracted text [l 240-246]
5) Get the tex text for the whole line [l 248-251]
6) Look for the best match from the pdf text to the tex text [l 255]. "Best" is defined here as longest matching substring containing the sync point. Ideally, this should be unique, but need not be (e.g. for the line "abc$abc$abc$abc$abc".
7) Cross-check in the other direction (i.e., from tex text to pdf text using the previously determined tex column as starting point) [l 261-267]
8) If a unique, 1:1 match is found, return that; otherwise, don't return any specific column information (thus matching the hole line/paragraph).

So essentially, TeXworks uses pdf boxes for text extraction/matching, not SyncTeX nodes.
