### ISSUE TITLE
Fine synchronization from pdf to tex fails between words

### ISSUE THREAD

**Issue by jlaurens** [TeXworks/texworks#804]
Typeset the following document with pdf latex in A4
```
\documentclass{minimal}
\begin{document}
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
\end{document}
```
The fourth line in the pdf output reads
```nulla pariatur. Excepteur...```

Fine synchronization from pdf to source works for 'a' from 'nulla' and 'p' from 'pariatur' but fails if we click on the space between the 'a' and the 'p'.

**Comment by stloeffler** [comment]
Yes. Fine sync works based on the character boxes in the pdf (used for text matching). Since the pdf library poppler does not report such boxes for spaces, this currently fails. While it might be possible to estimate such "space boxes", it would require an awful lot of assumptions (such as a homogeneous line height, a specific reading direction, a strictly monotonously increasing x coordinate). Such an algorithm would likely fail (as in: messing up large parts of the fine sync for the whole paragraph) in numerous cases, such as when math, diacritics etc. are involved.
Therefore, and because the typical use case is expected to be clicking on words, not spaces inbetween, this is unlikely to be implemented with the current approach.
