### ISSUE TITLE
I cannot figure out how to install mcode.sty from mathworks

### ISSUE THREAD

**Issue by jeremymatt** [TeXworks/texworks#828]
_Steps to reproduce the problem_:

I've tried doing this through the package manager (I get an "that directory does not appear to be a repository" error)

I've tried adding a root directory using the miktex settings program (gives a TDS directory error.  google is not helpful regarding what is a TDS-compliant directory or how I can create one)

I've tried navigating to the directory in cmd prompt and installing using "mpm.exe --admin --install {name}". THis gives the following error:
2017-09-22 19:15:55,355-0400 INFO  mpmcli - starting: mpmcli 2.9.6346 (MiKTeX 2.9.6350 64-bit)
2017-09-22 19:15:55,356-0400 INFO  mpmcli - Option --admin may require administrative privileges
2017-09-22 19:15:55,370-0400 INFO  mpmcli - Operating on the shared (system-wide) MiKTeX setup
2017-09-22 19:15:55,381-0400 FATAL mpmcli - MiKTeX encountered an internal error.
2017-09-22 19:15:55,381-0400 FATAL mpmcli - Info: 
2017-09-22 19:15:55,381-0400 FATAL mpmcli - Source: Libraries\MiKTeX\PackageManager\PackageManager.cpp
2017-09-22 19:15:55,381-0400 FATAL mpmcli - Line: 656
  

_Expected output_:

_Actual output_:

_TeXworks version_:  Version 0.6.2
_TeXworks obtained from_: 
_Operating system_:  windows 10

_Please provide any additional information below_:
I've spent a stupid amount of time on this (an hour or more) trying to get this working.  And this should be simple:
1) there's a package manager
2) the package manager shoudl be able to install packages.

**Comment by TorbjornT** [comment]
You're actually asking this in the wrong place, TeXworks being just an editor doesn't have anything to do with package installation. That belongs to [MikTeX](https://github.com/MiKTeX).

I don't use MikTeX myself, and I'm not really sure what you've done. I was under the impression that the package manager could only install packages from [the MikTeX repository](https://miktex.org/packages) (`mcode` is not found there), but perhaps I was wrong.

Anyway, for a one-off, place `mcode.sty` in the same folder as your `.tex` file, then it should work.

(Alternatively, instead of `mcode`, use the `matlab-prettifier` package which *is* in the MikTeX repository, and should be installable from the package manager. Example at https://tex.stackexchange.com/a/158816/.)
