### ISSUE TITLE
shortcuts for indent/unindent unreachable on some macOS keyboards

### ISSUE THREAD

**Issue by jlaurens** [TeXworks/texworks#834]
Hi,

The keyboard shortcut to comment is
⇧⌘]
whereas the keyboard shortcut to indent is
⌘]
unfortunately, there is not always a ']' key in the keyboard such that the above key combinations do not exist pas is. In order to produce the ']' character, one has to use the ⇧⌥) combination such that 
the shift key is always down and the second shortcut cannot be reached.

Some code editors use the key combination Tab/ shift+Tab to indent/unindent.
TeXworks could do the same.
Of course, that requires some works and some rule to allow the user to really insert some space instead of indenting.

_TeXworks version_: 0.6.2
_TeXworks obtained from_: Official repository
_Operating system_: macOS 10.13.1

**Comment by SuneKarlsson** [comment]
Just want to add that this is not only a Mac issue. It is an internationalization issue where the keyboard layout varies with the needs of your language (in my case Swedish) where these characters ( ],[ ) have been remapped to various key combinations (e.g. "Alt gr"+8 for [ on Windows) in order to leave space for all the letters of the alphabet (some of us have more than a-z).
This also affects the comment/uncomment facility in the editor.

**Comment by stloeffler** [comment]
As far as internationalization goes, the best place to handle the remapping of shortcuts would be the translation file. For Swedish, so far none exists, but everyone is very welcome to work on Swedish [translations of TeXworks](https://github.com/TeXworks/texworks/wiki/Translating)  ;-).
As a workaround, you can define your own mapping of shortcuts by means of a `shortcuts.ini` file in the TeXworks configuration directory - see the [manual](https://github.com/TeXworks/manual) for details

**Comment by SuneKarlsson** [comment]
Thanks! I managed eventually to figure out how to remap the shortcuts (to function keys as these seems to be unused by TeXworks). Thanks also for a great piece of software.

**Comment by stloeffler** [comment]
Tab/Shift-Tab have been implemented in 573455d. Closing this issue
