### ISSUE TITLE
TeXworks.Exe file description is too long

### ISSUE THREAD

**Issue by hellolj** [TeXworks/texworks#851]
On Windows,

Select a pdf file, right click. In context menu, choose "open with",

The description for TeXWorks.exe is ridiculously long:

![image](https://user-images.githubusercontent.com/3222248/49270988-b7c9bc00-f4a6-11e8-9797-000434efa1cc.png)

**Comment by Meago** [comment]
I have met the same problem, it is really too long. 
Suggest to delete it directly or change it to "GUI to TeX System".

**Comment by stloeffler** [comment]
This is not an issue in this upstream version of TeXworks but in the customization MiKTeX performs. Searching for "a graphical user interface" in this repository yields no results, but in MiKTeX is finds https://github.com/MiKTeX/miktex/blob/master/Programs/Editors/TeXworks/texworks.rc. I suspect that's where this issue is coming from. Please report it there.

**Comment by Meago** [comment]
I got it, thanks!
