### ISSUE TITLE
TeXworks doesn't set correctly the PATH on macOS

### ISSUE THREAD

**Issue by eg9** [TeXworks/texworks#861]
_Steps to reproduce the problem_:

Run a file `\input|"kpsewhich plain.tex"\bye` with pdftex from the menu

_Expected output_:

/usr/local/texlive/2019/texmf-dist/tex/plain/base/plain.tex

_Actual output_:

Nothing. The console shows

```
sh: kpsewhich: command not found
```

_TeXworks version_: 0.6.3
_TeXworks obtained from_: GitHub
_Operating system_: macOS Mojave 10.14

_Please provide any additional information below_:

If I define a “pdftex+shell-escape" engine and run a file containing

```tex
\input|"echo $PATH"
\bye
```
I get in the PDF file `/usr/bin:/bin:/usr/sbin:/sbin`.

If I launch TeXworks from a terminal with
```bash
/Applications/TeXworks.app/Contents/MacOS/TeXworks
```
the `PATH` variable is set correctly.

**Comment by stloeffler** [comment]
This seems to be a "feature" of Mac OS. Does https://superuser.com/questions/476752/setting-environment-variables-in-os-x-for-gui-applications help?

**Comment by eg9** [comment]
I saw the new version 0.6.4. The malfunctioning has not been fixed.

I repeat: version 0.6.2 executes shell commands without any problem on macOS 10.15 Catalina. So it is _not_ a macOS feature.

**Comment by stloeffler** [comment]
As far as I can tell, there was no change to the source code in TeXworks. 0.6.2 uses [`QProcess:systemEnvironment`](https://github.com/TeXworks/texworks/blob/7ecce17d7241bd8c3f683d5d74523ed14051e348/src/TeXDocument.cpp#L2644-L2698) in pretty much the same way as [0.6.3 does](https://github.com/TeXworks/texworks/blob/a2470cac986bab5c971ab80799b4c98cc055a6f7/src/Engine.cpp#L96-L141). Things were moved around a bit, but other than that nothing major changed.

It does generally seem to be a Mac OS "feature" (i.e. intended behavior) that GUI apps are treated differently than terminal apps (both Google and StackExchange have many hits for this topic, and there is even a [dedicated script](https://github.com/ersiner/osx-env-sync) intended to try mitigate this), and things seem to change from version of version of Mac OS X. From what I can tell (without having a Mac to test on), GUI apps are launched by some `launchctl` which has its own way of keeping track of/setting environment variables, but generally does not take `.bash_profile` and similar things into account.

About TeXworks 0.6.2. After a lot of digging, I seem to have found a difference in how Qt, the underlying framework used by TeXworks, handles environment variables. Tw 0.6.2 uses a version of Qt somewhere around 5.8.0, whereas Tw 0.6.3 uses Qt somewhere around 5.12.1 (could you verify that from Help > About TeXworks please?). Qt 5.8.0 uses the [`_NSGetEnviron` command](https://github.com/qt/qtbase/blob/49dc9aa409d727824f26b246054a22b5a7dd5980/src/corelib/io/qprocess.cpp#L2514), whereas Qt 5.12.1 uses [`NSProcessInfo`](https://github.com/qt/qtbase/blob/0c498153331d79715ecfe431eb27065748628ba8/src/corelib/io/qprocess_darwin.mm#L49). Why they changed that, what that entails, and whether or not that indeed causes the differences you see I don't know - the only way of finding out would be to compile Tw 0.6.3 (or 0.6.4) with Qt 5.8.0 or similar and try it out.

**Comment by stloeffler** [comment]
As documented, e.g., in [QTBUG-42656](https://bugreports.qt.io/browse/QTBUG-42656), an application launched from the GUI has different environmental variable settings than if launched from a terminal. Presumably, the reason is that the application inherits the environment of the calling process. If this is the terminal (e.g., bash), it will have parsed all sorts of config files (e.g., (`.bash_profile`) that will have modified the environment variables.

BTW, the same happens on Linux.

You can try redefining the typesetting tool to not run pdftex directly but rather a shell and pdftex in that shell. Maybe that would force the config files to be parsed...

Also note that Tw does not (directly) use $PATH. Instead, it keeps its own list of directories in which to look for TeX-related programs. By default, the directories in $PATH are added to the list, but you can also add your own (and they will have a higher priority than the auto-added ones). Thus, you could in principle have several side-by-side installations of TeX and quickly change between them by simply reordering the list. Because it keeps its own list, Tw does not rely on $PATH when executing programs but instead calls them with their full path.

For all these reasons, I currently see no way to easily implement what you want. TeXworks can only rely on the environment it gets during invocation - any custom parsing of config files is bound to break sooner or later; and forcefully messing with environment variables would probably break stuff, too.
