### ISSUE TITLE
dwmapi.dll is missing

### ISSUE THREAD

**Issue by Wymaxep2011** [TeXworks/texworks#873]
Good evening,

I was using TeXworks 0.4.4 for many years until now I found the CTAN ftp mirror (required for plugin installation) directory is empty. Soon it appeared that api.miktex.org was just dropped (very stupid solution, IMHO). While I'm looking a solution how to make a local plugin repository mirror, I decided to test newer TeXworks versions.

So, 0.6.3 and 0.6.2 fails to start with an error "dwmapi.dll not found". This library is absent in Windows XP and it looks like it's impossible to just copy it from some other Windows version. 
0.6.0 works fine. Honestly I did not install 0.6.1 but looked to the sources and found that configure.sh contains next lines:

0.6.2:
-DTEXWORKS_ADDITIONAL_LIBS='pcre16;opengl32;imm32;shlwapi;dwmapi;uxtheme'
0.6.1:
-DTEXWORKS_ADDITIONAL_LIBS='pcre16;opengl32;imm32;shlwapi'" 

Thus, the problem happened since 0.6.2 version. I don't see anything related in the incremental changes log https://raw.githubusercontent.com/TeXworks/texworks/release-0.6.3/NEWS
Could you please try to re-build the 0.6.3 without "dwmapi" library requirement? I don't know which exported functions do you use, but, IMO, it's possible to avoid this message using dynamic library import (LoadLibrary / GetProcAddress). I'm not good in C++ coding, since I use mainly Delphi and PHP for everything I need, so I'm afraid I'm not able to setup the environment necessary to compile this Win32 build to test it and cut off the calls that limits the OS support.

_TeXworks version_: 0.6.2
_TeXworks obtained from_: github
_Operating system_: WinXP SP3 x86

Thank you.

**Comment by stloeffler** [comment]
From what I can tell
* This dependency is caused by the current version of the underlying Qt framework TeXworks uses, not the TeXworks code itself. As such it unfortunately cannot be replaced easily.
* Windows XP support has officially been discontinued for years.
* From the internet (e.g. [here](https://www.lifewire.com/how-to-fix-dwmapi-dll-not-found-or-missing-errors-2623366)), it seems that Windows XP should have such a dll. I don't know if the XP version would be compatible due to its age, but at least it should be present. Please refer to your favorite search engine to figure out how to restore it if it's missing.

**Comment by stloeffler** [comment]
From https://forum.qt.io/topic/77135/dwmapi-dll-not-found, it seems that the last Qt version supporting Win XP was 5.6; the current automated builds use 5.12.3. However, if you really need it, you could probably compile TeXworks with Qt 5.6.

**Comment by Wymaxep2011** [comment]
Thank you for information, I will save Qt 5.6 for future use.
Nowadays I solved the auto-install plugins problem making the local repository, so I still able to use 0.6.0 version without forking.
In any case, it's better to study all risks before updating the third-party libraries. If update is required due to some specific functions that can't be replaced by other code - OK, but if update happened just because newer Qt was issued - that's bad idea.
