### ISSUE TITLE
0.6.3 in win10: 'file "" not found' errors when synchronizing still exist

### ISSUE THREAD

**Issue by lhomegit** [TeXworks/texworks#876]
_Steps to reproduce the problem_:

1.  open a tex file in texworks 0.6.3 
2. pdflatex 
3. Ctrl-left/right mouse button click in pdf
4. in pdf: right mouse button click menu does not contain item 'sync to source'

_Expected output_:
sync to source

_Actual output_:
'file "" not found' error, not sync

_TeXworks version_: 0.6.3
_TeXworks obtained from_: github
_Operating system_: windows 10

_Please provide any additional information below_:
sorry, not understand what can be useful ...

**Comment by stloeffler** [comment]
Just to confirm: you are definitely on 0.6.3, not 0.6.2 (I'm just asking because there was a big with pretty much the identical description fixed in ebd369c8c5cb234debac6cb7eb29655e1b08a820).
Do you have a .synctex.gz file alongside the .pdf file? When the pdf opens, does it display the path to the .synctex.gz file in the status bar at the bottom or does it say "No SyncTeX data available"?

**Comment by stloeffler** [comment]
Closed due to inactivity and outdated version of Tw.
