### ISSUE TITLE
typesetting a document with many components

### ISSUE THREAD

**Issue by jlaurens** [TeXworks/texworks#911]
**Is your feature request related to a problem? Please describe.**
Given a main.tex that includes chapter1.tex, chapter2.tex, ... that we both open in TW.
We can launch typesetting from any open editor. In case of error, the typesetting engine frequently waits for a user input, but we have to find out in which window we have to interact with the engine.

**Describe the solution you'd like**
1) If a typesetting process is launched from an editor window, a small red bullet could appear in front of the name in the window list. This bullet should be visible as long as the typesetting button variant is Stop.

2-a) TW could also prevent concurrent typesetting of the same document: display a dialog panel asking to stop the current process, very similar to the dialog panel used when trying to close a window with an attached typesetting process.

2-b) a simpler variant: while hitting the typeset button, if there is already a similar typesetting task running, switch to the window owning that task, otherwise do as usual.

**Comment by stloeffler** [comment]
I opted for solution 2b as it seems the least intrusive to me (if I click on the button, I see the typesetting - either because a new process is started or because the view switches to the currently running process).
Note that this only applies to source windows. The output window still allows to stop the process directly for backwards compatibility (and because there is typically a 1:1 correspondence between a pdf and a root document).

Re. solution 1, I fear that this could become quite cluttered (and hard to decipher) when people are working on several separate documents at the same time (because then you need to know which window belongs to which "project")
Re. solution 2a, I am reluctant to ask users to stop a process that they can't see (and so they don't know if the process is waiting for input, running normally, ...).
