### ISSUE TITLE
Add other colour schemes for the UI

### ISSUE THREAD

**Issue by concastinator** [TeXworks/texworks#921]
**Is your feature request related to a problem? Please describe.**

Whenever possible, I try to configure my programs to use a dark colour theme, to diminish visual fatigue. Sadly, TeXworks offers a single, default, "black text on white background" colour scheme.

**Describe the solution you'd like**

I would like future versions of TeXworks to offer a menu option giving one the possibility to choose among several colour schemes, including the option to define one's own scheme (or alter the predefined ones).

**Describe alternatives you've considered**

Using TeXmaker (or TeXstudio), which offer this option. :)

**Comment by concastinator** [comment]
Well, it seems that I am not the first one to miss this configuration option: one has issue #164 (the first request in that discussion dates from August 10, 2009!) and there are also plenty of results when searching the internet, such as [this TeX.StackExchange question](https://tex.stackexchange.com/questions/383271/how-can-i-set-a-dark-theme-in-texworks). Not a good sign...

**Comment by stloeffler** [comment]
The style of the application can be customized (see https://github.com/TeXworks/texworks/issues/164#issuecomment-80294405). Similar to keyboard shortcuts, this currently has to be done by supplying a special text file for now.

Since nobody has contributed stylefiles yet (note that I am not a design expert), there is no list to choose from (and hence #164 is still left open.
