### ISSUE TITLE
An error window appears while opening a pdf file

### ISSUE THREAD

**Issue by andhla** [TeXworks/texworks#938]
**Bug description:**

When I try open pdf file error window is showed.
Log file (a few last line):
2021-06-05 15:44:49,572+0200 INFO  texworks - starting: MiKTeX TeXworks 0.6.6 (MiKTeX 21.3)
2021-06-05 15:44:49,572+0200 INFO  texworks -   argument(s): D:\SzkoĹ‚a\SzkoĹ‚a rok 2020-2021\Matematyka\Zadania dodatkowe\Klasy\Klasa 2CDMp\out.pdf
2021-06-05 15:44:53,029+0200 FATAL texworks - std exception: UTF-8 conversion failed; func=miktex_utf8__open, utf8="D:/Szkoła/Szkoła rok 2020-2021/Matematyka/Zadania dodatkowe/Klasy/Klasa 2CDMp/out.synctex"

If path to file not include Polish characters all is OK.
If path to file include Polish characters -> Error window.

**Steps to reproduce the problem:**

1. Opening any file with path that include Polish characters
2. 
3. 

**Expected behavior:**

**General information:**
_TeXworks version_: 0.6.6
_TeXworks obtained from_: MikTeX 21.3
_Operating system_: Windows 7

**Additional information:**

**Comment by stloeffler** [comment]
Thanks for reporting. From the error message, it would look as if this is a problem in the way MiKTeX interfaces with TeXworks. If that's the case, please report it to the MiKTeX project.

To clarify this, a couple of questions:
* Does this occur when launching a file from the Windows explorer, or also when using File > Open within TeXworks?
* Does the same problem occur when using TeXworks obtained from GitHub or the latest [nightly build](https://nightly.link/TeXworks/texworks/workflows/cd/master) (if you use the .zip file instead of the installer, it should be no problem to have it coexistent with the MiKTeX installation)

**Comment by andhla** [comment]
Error occur when launching a file from the Windows explorer.
TeXworks obtained from GitHub is OK.
I replace miktex-texworks.exe and TeXworks.exe in MiKTeX bin directory with TeXworks.exe obtained from GitHub
and now is OK.

**Comment by stloeffler** [comment]
Thanks for testing. So it's indeed a problem with some MiKTeX modification. Please report it to the MiKTeX developers so they can (hopefully) fix the issue.
