### ISSUE TITLE
TeXworks error

### ISSUE THREAD

**Issue by EgidijusB** [TeXworks/texworks#967]
Hi,
I try to run the typesetting for a template I have recently downloaded from TeXworks. The typesetting stops with an error:

**** Unable to open the initial device, quitting.
epstopdf ($Id: epstopdf.pl 48681 2018-09-16 23:03:58Z karl $) 2.28
!!! Error: Writing to c:\texlive\2021\texmf-dist\scripts\epstopdf/../../../tlpkg/tlgs/bin/gswin32c failed, error code 1

Could you help with solving this problem?

**Comment by stloeffler** [comment]
To (potentially) help, more information is necessary. However, at first glance, this doesn't seem to be a problem with the TeXworks code itself, but rather with some configuration or missing package/program. If that is the case, the problem is probably better discussed on the [mailing list](https://tug.org/mailman/listinfo/texworks).
Further information that would be helpful:
* Which version of TeXworks do you use?
* Where did you obtain TeXworks from?
* What operating system do you use?
* Can you provide a minimal example for which the error occurs (e.g., the template you use)?
* What typesetting tool do you use?
* Does `c:\texlive\2021\texmf-dist\tlgs/bin/gswin32c` (or another installation of ghostscript) exist on your machine?

**Comment by stloeffler** [comment]
Closed due to inactivity
