### ISSUE TITLE
PATH environment variable not handled correctly on Windows

### ISSUE THREAD

**Issue by ghertlei** [TeXworks/texworks#969]
**Bug description:**
On Windows TeXworks treats the PATH variable name as case-sensitive, although in Windows environment variable names are case-insensitive. There are many bug reports (e.g. #861) on the Web, but the issue has not yet been resolved or debugged so far.

**Steps to reproduce the problem:**

1. I installed MiKTeX 22.3-x64 on a newly installed Windows 10 system. --> everything works.
2. I installed MiKTeX 22.3-x64 on a Windows 10 system with many other pre-installed applications --> TeXworks aborts with an error message that Pygmentize cannot be found although it has been properly installed
3. (lengthy) analysis showed that texworks installs an additional PATH (name in all uppercase) although Windows uses the name "Path" (mixed upper and lower case). The process environment now has two path variables, "PATH" and "Path". Depending on which one appears first in the environment list, additional tools like Pygmentize are found or not.

**Expected behavior:**
TeXworks needs to process environment variables names in a case-insensitive mode on Windows. When it finds that the path env variable is called "Path", it needs to extend that variable (if needed) and not create a new "PATH" variable.

Workaround (e.g. in a wrapper WinTexWorks.cmd script): (replaces Windows original variable "Path" by "PATH" to avoid the bug in TeXworks)
```
@echo off
set XP=%PATH%
set Path=
set PATH=%XP%

start /B TeXworks %*
```

**General information:**
_TeXworks version_: 0.6.7 (MiKTeX 22.3)
_TeXworks obtained from_: MiKTeX package 22.3
_Operating system_: Windows 10 20H2

**Additional information:**

**Comment by stloeffler** [comment]
Thanks for debugging and reporting.
In my test (TeXworks 0.6.7 obtained from GitHub on Windows 7), no `PATH` variable was added (only the system's `Path` was present). I used a custom typesetting tool which simply ran `set` on the command line to check the environment variables.
Generally, TeXworks should not modify `PATH` on Windows (or on Linux; only on macOS, some additions are made - see #861 ).

Could you please try with TeXworks from GitHub to check if this is an issue caused by some MiKTeX changes? (this generally should be runable independent of the MiKTeX version).

**Comment by ghertlei** [comment]
I have debugged the MiKTeX wrapper libraries inserted into TeXworks.
The problem is actually in MiKTeX code SessionImpl::CreateChildEnvironment().

I have created a new issue: https://github.com/MiKTeX/miktex/issues/1089

and will close this one.
